version: "3.9"

services:
  postgis:
    image: postgis/postgis:13-3.5
    platform: linux/amd64
    container_name: rnb-postgis
    restart: unless-stopped
    env_file:
      - ./../.env.dev
    ports:
      - "5432:5432"
    volumes:
      - postgis-data:/var/lib/postgresql/data
      # - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgis-data:
